Repository FRONTENDBOOTCAMP-13th/winningEleven, pull requests merged in 2025-03, with the labels that each got.

#4 Feat: 페이지별 폴더 분배
  src/pages/donghwan/index.html
  src/pages/hyongju/index.html
  src/pages/jisu/index.html
  src/pages/soonhyuk/index.html
  src/pages/yerin/index.html
Labels: Feat

#6 Feat: assets 추가
  index.html
  src/pages/jisu/assets/Q&A.svg
  src/pages/jisu/assets/close.svg
  src/pages/jisu/assets/detailCard.svg
  src/pages/jisu/assets/heart.svg
  src/pages/jisu/assets/information.svg
  src/pages/jisu/assets/more.svg
  src/pages/jisu/assets/password.svg
  src/pages/jisu/assets/pencil.svg
  src/pages/jisu/assets/people.svg
  src/pages/jisu/assets/profile.svg
  src/pages/jisu/assets/speech.svg
  src/pages/jisu/assets/state=Default.svg
  src/pages/jisu/assets/state=focus.svg
Labels: Feat

#7 Feat: assets 파일 생성
  src/pages/donghwan/assets/down.svg
  src/pages/donghwan/assets/hamburger.svg
  src/pages/donghwan/assets/share.svg
Labels: Feat

#8 assets폴더 생성 및 svg 파일 추가하기
  src/pages/yerin/assets/call.svg
  src/pages/yerin/assets/flag.svg
  src/pages/yerin/assets/heart-stright.svg
  src/pages/yerin/assets/keyboard.svg
  src/pages/yerin/assets/photo.svg
  src/pages/yerin/assets/question.svg
  src/pages/yerin/assets/scan.svg
  src/pages/yerin/assets/won.svg
Labels: Feat

#9 svg 이미지 생성
  src/pages/hyongju/assets/battery.svg
  src/pages/hyongju/assets/celluar.svg
  src/pages/hyongju/assets/chat.svg
  src/pages/hyongju/assets/check.svg
  src/pages/hyongju/assets/direction=down.svg
  src/pages/hyongju/assets/direction=left.svg
  src/pages/hyongju/assets/direction=right.svg
  src/pages/hyongju/assets/direction=up.svg
  src/pages/hyongju/assets/fullChat.svg
  src/pages/hyongju/assets/fullFile.svg
  src/pages/hyongju/assets/fullHome.svg
  src/pages/hyongju/assets/fullMap.svg
  src/pages/hyongju/assets/fullMy.svg
  src/pages/hyongju/assets/home.svg
  src/pages/hyongju/assets/life.svg
  src/pages/hyongju/assets/logo.svg
  src/pages/hyongju/assets/lte.svg
  src/pages/hyongju/assets/map.svg
  src/pages/hyongju/assets/my.svg
  src/pages/hyongju/assets/navItem.svg
  src/pages/hyongju/assets/plus.svg
  src/pages/hyongju/assets/position.svg
  src/pages/hyongju/assets/search.svg
Labels: Feat

#10 Hong 01
  src/pages/soonhyuk/assets/calender-black.svg
  src/pages/soonhyuk/assets/fullpeople-black.svg
  src/pages/soonhyuk/assets/minus.svg
  src/pages/soonhyuk/assets/organizer.svg
  src/pages/soonhyuk/assets/send.svg
  src/pages/soonhyuk/assets/sex.svg
  src/pages/soonhyuk/assets/smile.svg
  src/pages/soonhyuk/assets/time.svg
Labels: Feat

#23 design: 디자인 시스템 템플릿 적용
  src/style.css
Labels: Design

#21 Feat: 프로필컨텐츠 제작 #13
  src/pages/jisu/index.html
  src/pages/jisu/profile-contents.html
Labels: Feat, Rename

#26 Feat: profile 컴포넌트 추가(#15 ~ #20), Fix: #13 폰트 크기 수정
  src/pages/jisu/profile-checkbox.html
  src/pages/jisu/profile-choiceButton.html
  src/pages/jisu/profile-closed-unclosed.html
  src/pages/jisu/profile-contents.html
  src/pages/jisu/profile-icon-balloon.html
  src/pages/jisu/profile-text-icon.html
Labels: Feat, Fix

#31 Feat: Q&A 컴포넌트 제작(#12,#22,#30)/ assets: svg 파일 추가 (#29)
  src/pages/yerin/assets/calender.svg
  src/pages/yerin/assets/check.svg
  src/pages/yerin/assets/plus.svg
  src/pages/yerin/assets/send.svg
  src/pages/yerin/assets/speech.svg
  src/pages/yerin/assets/thumbsup.svg
  src/pages/yerin/components/check.html
  src/pages/yerin/components/info.html
  src/pages/yerin/components/text-img.html
Labels: Feat

#34 feat: region&menu bar 제작
  index.html
  src/assets/alrambell.svg
  src/components/main/region&menubar.html
Labels: Feat

#41 feat: Q&A 컴포넌트 제작
  src/components/q&a/badge.html
  src/components/q&a/img-text.html
  src/components/q&a/message.html
  src/components/q&a/nav.html
  src/components/q&a/profile&nickname.html
Labels: Feat

#42 Feat: navItem 구현
  src/components/main/navMenubar.html
  src/style.css
Labels: Feat

#44 feat: storyfield 제작
  public/img/whatNono.webp
  src/components/main/storyField.html
Labels: Feat

#45 Feat: page4의 프로필 페이지 제작 #35
  src/assets/profile.png
  src/assets/smile.png
  src/assets/speech.svg
  src/pages/profilePage/profile.html
Labels: Feat, Design

#48 Fix: profile페이지 px 값과 하단바 추가+상태 수정 / Feat: profileCard 페이지 제작
  src/pages/profilePage/profile.html
  src/pages/profilePage/profileCard.html
Labels: Feat, Fix

#52 시작페이지와 로그인, 회원가입 페이지 만들기
  src/assets/check.svg
  src/assets/plus.svg
  src/assets/positionWhite.svg
  src/components/start/Navitems.html
  src/components/start/back.html
  src/components/start/button.html
  src/components/start/category.html
  src/components/start/keyboard.html
  src/components/start/start.html
  src/components/start/time&cellular.html
  src/pages/startPage/category.html
  src/pages/startPage/login.html
  src/pages/startPage/login2.html
  src/pages/startPage/signup.html
  src/pages/startPage/signup2.html
  src/pages/startPage/start.html
  src/style.css
Labels: Feat

#56 feat: listItem 및 하위컴포넌트 제작
  src/components/main/listItem.html
Labels: Feat

#58 Feat: profileDetails 페이지 제작 #57
  src/assets/plusButton.svg
  src/pages/profilePage/profileDetails.html
Labels: Feat

#59 feat: q&a 페이지 제작
  src/assets/finish.svg
  src/assets/finish_black.svg
  src/assets/thumbsup.svg
  src/components/q&a/check.html
  src/components/q&a/text-img.html
  src/pages/q&aPage/boardq&a.html
  src/pages/q&aPage/q&a.html
  src/pages/q&aPage/writeq&a.html
Labels: Feat

#60 Feat: person1~3,inforitems1~2,withUs create
  src/components/board/components.html
Labels: Feat

#62 Feat: plusButton 컴포넌트 제작
  src/components/main/plusButton.html
  src/style.css
Labels: Feat

#68 Feat: profileDetail 체크박스 반응 추가
  src/pages/profilePage/checkbox.js
  src/pages/profilePage/profileDetails.html
Labels: Feat, Fix

#76 feat: buttonItemsBar 제작
  src/components/main/buttonItemsBar.html
Labels: Feat

#77 feat: inputBar 제작
  src/components/main/inputBar.html
Labels: Feat

#78 feat: etcButtons 제작
  src/components/main/etcButtons.html
Labels: Feat

#80 스타트 페이지 플로우 및 태그 점검
  src/pages/startPage/category.html
  src/pages/startPage/signup.html
  src/pages/startPage/start.html
Labels: Feat

#83 feat:공통 컴포넌트 추가 제작 #67
  src/components/board/components.html
Labels: Feat

#84 Fix: profileDetails 접근성 개선
  src/pages/profilePage/profileDetails.html
Labels: Fix

#89 Page4 - profile 접근성 개선
  src/pages/profilePage/profile.html
Labels: Fix

#92 feat: exchangePage UI 제작
  src/pages/mainpage/exchangePage.html
  src/pages/mainpage/mainPage.html
Labels: Feat

#94 Page 4 - profile 코드 수정
  src/pages/profilePage/profile.html
Labels: Design, Fix

#99 포커스 라인 수정 및 오류와 디자인 태그 정상화
  src/pages/startPage/category.html
  src/pages/startPage/login.html
  src/pages/startPage/login2.html
  src/pages/startPage/signup.html
  src/pages/startPage/signup2.html
  src/pages/startPage/start.html
Labels: Feat, Fix

#104 feat: productinfoPage-UI 제작
  public/img/profile.png
  public/img/smile.png
  src/pages/mainpage/.gitkeep
  src/pages/mainpage/exchangePage.html
  src/pages/mainpage/productInfoPage.html
Labels: Feat

#105 feat: Q&A page 수정, 버튼 추가, 접근성 개선
  src/components/q&a/message.html
  src/components/q&a/nav.html
  src/components/q&a/text-img.html
  src/pages/q&aPage/boardq&a.html
  src/pages/q&aPage/chatContent.html
  src/pages/q&aPage/chatList.html
  src/pages/q&aPage/q&a.html
  src/pages/q&aPage/writeq&a.html
Labels: Feat

#108 Page 4 - profileDetails 모달 추가
  src/pages/profilePage/checkbox.js
  src/pages/profilePage/profileDetails.html
Labels: Feat

#110 컴포넌트 수정 및 접근성 관리
  src/components/start/Navitems.html
  src/components/start/back.html
  src/components/start/button.html
  src/components/start/category.html
  src/components/start/signupNumber.html
  src/components/start/signupText.html
  src/pages/startPage/category.html
  src/pages/startPage/login.html
  src/pages/startPage/login2.html
  src/pages/startPage/signup.html
  src/pages/startPage/signup2.html
  src/pages/startPage/start.html
Labels: Feat, Fix

#111 Feat:컴퍼넌트 제작 pt3 #90
  src/components/board/components.html
Labels: Feat

#114 feat: page5 너비 설정, nav 추가
  src/pages/q&aPage/boardq&a.html
  src/pages/q&aPage/chatContent.html
  src/pages/q&aPage/chatList.html
  src/pages/q&aPage/q&a.html
  src/pages/q&aPage/writeq&a.html
Labels: Design, Fix

#117 Page4 연결 및 너비 수정
  src/pages/profilePage/profile.html
  src/pages/profilePage/profileCard.html
  src/pages/profilePage/profileDetails.html
Labels: Fix

#118 Dongfa/feat/search page
  index.html
  public/favicon-16x16.png
  src/assets/IOSkeypad.svg
  src/pages/mainpage/exchangePage.html
  src/pages/mainpage/mainPage.html
  src/pages/mainpage/productInfoPage.html
  src/pages/mainpage/searchPage.html
  src/style.css
Labels: Feat, Design, Fix

#119 feat: q&a nav 수정, 링크 연결
  index.html
  src/pages/q&aPage/boardq&a.html
  src/pages/q&aPage/chatContent.html
  src/pages/q&aPage/chatList.html
  src/pages/q&aPage/q&a.html
  src/pages/q&aPage/writeq&a.html
Labels: Feat, Fix

#122 feat: Common components 완료 및 오타수정 및 svg파일 2개 생성#112
  src/assets/state=Default2.svg
  src/assets/state=focus2.svg
  src/components/board/components.html
Labels: Feat

#124 리드미 초안 작성
  README.md
Labels: Docs

#125 page5 글자 크기 수정, 사진 추가
  src/pages/q&aPage/boardq&a.html
  src/pages/q&aPage/chatContent.html
  src/pages/q&aPage/chatList.html
  src/pages/q&aPage/q&a.html
  src/pages/q&aPage/writeq&a.html
Labels: Feat

#126 feat: boardpage creating #121
  src/pages/boardPage/board1.html
Labels: Feat

#129 ETC: 프로젝트 디자인 시스템 소개 페이지 제작
  src/pages/componentsPage/designSystem.html
Labels: ETC

#130 컴포넌트 페이지 제작 및 오류 수정
  src/assets/plus.svg
  src/pages/componentsPage/button.html
  src/pages/componentsPage/header&nav.html
  src/pages/componentsPage/input.html
  src/pages/componentsPage/textfield.html
  src/pages/q&aPage/boardq&a.html
  src/pages/q&aPage/q&a.html
Labels: Feat, ETC

#132 feat: png 파일 추가, 코드 수정
  public/img/badge.png
  src/pages/q&aPage/boardq&a.html
  src/pages/q&aPage/writeq&a.html
Labels: Feat, Design

#137 profile 페이지들 레이아웃 및 하단바 링크 적용
  src/pages/profilePage/profile.html
  src/pages/profilePage/profileCard.html
  src/pages/profilePage/profileDetails.html
Labels: Design, Fix

#138 페이지 연결 및 코드 수정
  src/pages/q&aPage/boardq&a.html
  src/pages/q&aPage/chatContent.html
  src/pages/q&aPage/chatList.html
  src/pages/q&aPage/q&a.html
  src/pages/q&aPage/writeq&a.html
Labels: Design

#142 fix: 전체 페이지 플로우 연결 1차
  src/pages/mainpage/exchangePage.html
  src/pages/mainpage/mainPage.html
  src/pages/mainpage/productInfoPage.html
  src/pages/mainpage/searchPage.html
  src/pages/q&aPage/boardq&a.html
  src/pages/startPage/signup2.html
Labels: ETC

#145 배포 페이지 텍스트 센터 수정
  src/pages/startPage/login.html
  src/pages/startPage/login2.html
  src/pages/startPage/signup.html
  src/pages/startPage/signup2.html
Labels: Fix

#148 fix: q&a page 수정
  src/pages/q&aPage/boardq&a.html
  src/pages/q&aPage/chatContent.html
  src/pages/q&aPage/chatList.html
  src/pages/q&aPage/q&a.html
  src/pages/q&aPage/writeq&a.html
Labels: Fix

#149 체크박스 경로 수정
  src/pages/profilePage/profileDetails.html
Labels: Fix

#151 하단 마진 및 빼먹은거 수정
  src/pages/startPage/login2.html
  src/pages/startPage/signup.html
Labels: Fix

#154 레이아웃 서식
  src/pages/startPage/category.html
  src/pages/startPage/login.html
  src/pages/startPage/login2.html
  src/pages/startPage/signup.html
  src/pages/startPage/signup2.html
  src/pages/startPage/start.html
Labels: Fix

#155 fix: 에러 코드 수정
  src/pages/q&aPage/boardq&a.html
  src/pages/q&aPage/chatList.html
  src/pages/q&aPage/q&a.html
  src/pages/q&aPage/writeq&a.html
Labels: Fix

#156 Dongfa/etc/test build
  index.html
  public/img/dongfa.jpeg
  public/img/hyongju.png
  public/img/jisu.png
  public/img/soonhyuk.jpeg
  public/img/teamlogo.png
  public/img/yerin.jpeg
  src/pages/boardPage/.gitkeep
  src/pages/mainpage/exchangePage.html
  src/pages/mainpage/mainPage.html
  src/pages/mainpage/productInfoPage.html
  src/pages/profilePage/.gitkeep
  src/pages/q&aPage/.gitkeep
  src/pages/startPage/.gitkeep
Labels: ETC

#157 fix: 태그 에러 수정, 코드 수정
  src/pages/q&aPage/boardq&a.html
  src/pages/q&aPage/chatContent.html
  src/pages/q&aPage/chatList.html
  src/pages/q&aPage/q&a.html
  src/pages/q&aPage/writeq&a.html
Labels: Fix

#160 태그 유효성 검사 및 수정, 파비콘 연결
  src/pages/profilePage/checkbox.js
  src/pages/profilePage/profile.html
  src/pages/profilePage/profileCard.html
  src/pages/profilePage/profileDetails.html
Labels: Fix

#161 차형주 최종 수정
  src/components/start/Navitems.html
  src/components/start/back.html
  src/components/start/button.html
  src/components/start/category.html
  src/components/start/keyboard.html
  src/components/start/signupNumber.html
  src/components/start/signupText.html
  src/components/start/start.html
  src/components/start/time&cellular.html
  src/pages/componentsPage/button.html
  src/pages/componentsPage/header&nav.html
  src/pages/componentsPage/input.html
  src/pages/componentsPage/textfield.html
  src/pages/startPage/category.html
  src/pages/startPage/login.html
  src/pages/startPage/login2.html
  src/pages/startPage/signup.html
  src/pages/startPage/signup2.html
  src/pages/startPage/start.html
Labels: Design

#164 fix: 담당 페이지 웹표준, 웹접근성 관련 수정
  index.html
  src/pages/mainpage/exchangePage.html
  src/pages/mainpage/mainPage.html
  src/pages/mainpage/productInfoPage.html
  src/pages/mainpage/searchPage.html
  src/style.css
Labels: Fix

#165 프로필 png webp 변환
  public/img/profile.webp
  src/pages/profilePage/profile.html
  src/pages/profilePage/profileCard.html
Labels: Fix

#166 board1 page create #135
  src/pages/boardPage/board1.html
Labels: Feat

#169 리드미 링크 수정, png 변환
  README.md
  index.html
  public/img/badge.png
  public/img/badge.webp
  public/img/dongfa.jpeg
  public/img/dongfa.webp
  public/img/fighting_people.png
  public/img/fighting_people.webp
  public/img/hyongju.png
  public/img/hyongju.webp
  public/img/jisu.png
  public/img/jisu.webp
  public/img/profile.png
  public/img/smile.png
  public/img/smile.webp
  public/img/soonhyuk.jpeg
  public/img/soonhyuk.webp
  public/img/teamlogo.png
  public/img/teamlogo.webp
  public/img/whatNono.webp
  public/img/yerin.jpeg
  public/img/yerin.webp
  src/pages/componentsPage/textfield.html
  src/pages/mainpage/mainPage.html
  src/pages/mainpage/productInfoPage.html
  src/pages/profilePage/profile.html
  src/pages/q&aPage/boardq&a.html
Labels: Docs, Fix, Rename, Remove

#171 fix: 최종 수정
  src/pages/q&aPage/chatList.html
Labels: Fix

#173 Docd: 리드미 완성
  README.md
Labels: Docs
